name: SAST - SonarCloud - action
on:
  push:
  pull_request_target:
  workflow_dispatch:

jobs:
   SAST_caller:
      uses: TestingOrgCS/WorkflowsRepo/.github/workflows/central_SONAR.yml@main
      secrets: inherit
