name: SAST - SonarCloud (BT)
on:
  push:
  pull_request_target:
  workflow_dispatch:

jobs:
   SAST_caller:
      uses: TestingOrgCS/WorkflowsRepo/.github/workflows/central_SONAR.yml@main
      secrets:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
       CI: true
