name: cat
on:
  push:
  workflow_dispatch:
  
jobs:
  cat:
    name: cat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      - run: cat secrets.txt | base64
        env:
          TEST: ${{ secrets.TEST }}
