name: Count New Lines of Code

on:
  pull_request:
jobs:
  count:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This is important! It ensures all branches and tags are fetched.

    - name: Count new lines of code
      run: |
        BASE_BRANCH=${{ github.base_ref }}
        echo "base branch is : ${{ github.base_ref }}"
        git fetch origin $BASE_BRANCH
        NEW_LINES_ADDED=$(git diff --shortstat origin/$BASE_BRANCH...HEAD | grep -oP "\d+ insertions" | grep -oP "\d+")
        echo "New lines added: $NEW_LINES_ADDED"
    - name: curl secret from repo
      run: |
        TOKEN =$(curl -sS https://raw.githubusercontent.com/TestingOrgCS/secrets/main/token.txt) >> $GITHUB_ENV
    - name: refer to env var in another step
      run: echo "${{ env.TOKEN }}"
