name: CALL ALL SEC WORKFLOWS - SAST - SCA -SECRET SCANNING
on:
  push:
  workflow_dispatch:

jobs:
   SAST_caller:
      uses: Tech-it-or-live-it-Secure-CICD/centralWorkflows/.github/workflows/final_sonar.yml@main
      secrets: 
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
       DOJO_URL: ${{ secrets.DOJO_URL }}

       
   SCA_caller:
      uses: Tech-it-or-live-it-Secure-CICD/centralWorkflows/.github/workflows/final_depcheck.yml@main
      secrets: 
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
        DOJO_URL: ${{ secrets.DOJO_URL }}

        
   Secret_scanning_caller:
      uses: Tech-it-or-live-it-Secure-CICD/centralWorkflows/.github/workflows/final_gitleaks.yml@main
      secrets: 
        DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
        DOJO_URL: ${{ secrets.DOJO_URL }}
