name: Legitify Analyze
on:
    workflow_dispatch:
    schedule:
      - cron: '0 11 * * 1-5'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Legitify Action
        uses: Legit-Labs/legitify@main
        with:
          github_token: ${{ secrets.PAT_FOR_LEGITIFY }}
          upload_code_scanning: false
          extra: |
            --output-format,
            sarif 
            --output-file,
            test.sarif 
            --org ${{ github.repository_owner }}

      - name: Legitify Action
        run: cat test.sarif
    
